# [OpenAI] - Category_Attributes \uC784\uBCA0\uB529 \uBC0F GPT \uBAA8\uB378\uC6A9
openai.api.key=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

# [Google] - Gemini \uBAA8\uB378\uC6A9
google.api.key=AIzaSyDotaVVtOUm4-I2AxuiuyPatmCE86RKHb8

# [perplexity] - perplexity \uBAA8\uB378\uC6A9
perplexity.api.key=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

# [Database] - Docker\uB85C \uB744\uC6B4 PostgreSQL \uC815\uBCF4
spring.datasource.password=AIQ1324

google.search.cx=42e3c95953b554266